"""Seed initial data

Revision ID: 05e9f202542d
Revises: 222d5a357d3b
Create Date: 2025-09-09 15:21:03.169304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e9f202542d'
down_revision: Union[str, None] = '222d5a357d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Seed Buildings
    op.execute(
        """
        INSERT INTO buildings (id, address, latitude, longitude) VALUES
        (1, 'г. Москва, ул. Ленина 1, офис 3', 55.7558, 37.6173),
        (2, 'г. Новосибирск, ул. Блюхера, 32/1', 55.0084, 82.9357);
        """
    )

    # Seed Activities
    op.execute(
        """
        INSERT INTO activities (id, name, parent_id) VALUES
        (1, 'Еда', NULL),
        (2, 'Мясная продукция', 1),
        (3, 'Молочная продукция', 1),
        (4, 'Автомобили', NULL),
        (5, 'Грузовые', 4),
        (6, 'Легковые', 4),
        (7, 'Запчасти', 6),
        (8, 'Аксессуары', 6);
        """
    )

    # Seed Organizations
    op.execute(
        """
        INSERT INTO organizations (id, name, building_id) VALUES
        (1, 'ООО "Рога и Копыта"', 1),
        (2, 'ПАО "Мясокомбинат"', 2),
        (3, 'Молочный завод "Зорька"', 2);
        """
    )

    # Seed Phone Numbers
    op.execute(
        """
        INSERT INTO phone_numbers (organization_id, number) VALUES
        (1, '2-222-222'),
        (1, '3-333-333'),
        (2, '8-923-666-13-13');
        """
    )

    # Seed Organization-Activity Associations
    op.execute(
        """
        INSERT INTO organization_activity (organization_id, activity_id) VALUES
        (1, 3),
        (2, 2),
        (3, 3);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM organization_activity;")
    op.execute("DELETE FROM phone_numbers;")
    op.execute("DELETE FROM organizations;")
    op.execute("DELETE FROM activities;")
    op.execute("DELETE FROM buildings;")
    # ### end Alembic commands ###
